In [10]:
from math import *
from leg import *
import numpy as np

In [4]:

x,y,z=1,0.2,-1.8
leg1 = QuadLeg(1, 'fr', Point(), 2, 2, ServoIds(1,2,3))
pos1 = Point(x, y, z)
ang1 = leg1.get_angles(pos1)
print(ang1)
rpos1 = leg1.get_toe_pos(ang1)
print(pos1, rpos1)
print("Good!" if pos1==rpos1 else "Bad :-(")

AttributeError: 'ParamGroup' object has no attribute 'values'

In [12]:
good = True
for pos in [(0.3, 0, -1.8),
            (0.4, 0, -1.8),
            (0.6, 0, -1.7),
            (0.6, 0, -1.6),
           (0.8, 0, -1.6),
           (0.9, 0, -1.5),
           (1, 0, -1.8),
           (1, 0, -2),
           (1, 0, -2.3),
           (1, 0, -3),
           (1.2, 0, -3.6),
           (1, 0.5, -3),
            (1, -0.5, -3),
           (1, 1, -3),
           (1, -1, -3),
           (0, 0.2, -3),
           (-1, 0.4, -3.2)]:
    p = Point(*pos)
    ang1 = leg1.get_angles(p)
    rp = leg1.get_toe_pos(ang1)
    if rp!=p:
        print("Bad!: ", p, rp, '\n', ang1)
        good = False
if good:
    print("All tests passed!")

All tests passed!


In [13]:
x,y,z=0, 0.2, -3
leg1 = QuadLeg(1, Point(), 'fr', 2, 2, ServoIds(1,2,3))
ang1 = leg1.get_angles(pos1)
print(ang1)
rpos1 = leg1.get_toe_pos(ang1)
print(pos1.p, rpos1.p)
print(equal( pos1.p[0], rpos1.p[0]), equal(pos1.p[1], rpos1.p[1]), equal(pos1.p[2], rpos1.p[2])) 
print(abs(pos1.p[0]- rpos1.p[0]))
print("Good!" if pos1==rpos1 else "Bad :-(")

LegAngles(cox_angle=96.3401917459099, femur_angle=29.949491583397638, tibia_angle=62.28977795074845)
[ 1.   0.2 -1.8  1. ] [ 1.   0.2 -1.8  1. ]
True True True
1.1102230246251565e-16
Good!


In [14]:
target = Point(1, 1, -3)
leg1.goto(Point(0, 0, -3))
print(leg1.step(StepPhase.clear, target))
print(leg1.step(StepPhase.lift, target))
print(leg1.step(StepPhase.drop, target))
print(leg1.step(StepPhase.pose, target))


TypeError: Leg.goto() missing 1 required positional argument: 'actions'

In [ ]:
a1=20.0
a2=30.0
a3=(a1+a2)/2
t1=Transform()@Transform.xrot(a1)@Transform.yrot(a1)@Transform.zrot(a1)
t2=Transform()@Transform.xrot(a2)@Transform.yrot(a2)@Transform.zrot(a2)
t3=Transform()@Transform.xrot(a3)@Transform.yrot(a3)@Transform.zrot(a3)
t4=Transform((t1.m+t2.m)/2)
t5=t3.m-t4.m

In [ ]:
print(t1)
print(t2)
print(t3)
print(t4)
print(t5)

In [ ]:
v1=Point(0.5,0.5,0.5)
print(v1@t1)
print(v1@t2)
print(v1@t3)
print(v1@t4)

In [21]:
l1 = Point(1,1,0)
l2 = Point(1,-1,0)
l3 = Point(-1,1,0)
l4 = Point(-1,-1,0)
t1 = Transform.zrot(45).xlate(Point(1,0,0))
print(t1)
print(l1@t1-l1)
print(l2@t1-l2)
print(l3@t1-l3)
print(l4@t1-l4)

[[ 0.707 -0.707  0.     0.   ]
 [ 0.707  0.707  0.     0.   ]
 [ 0.     0.     1.     0.   ]
 [ 1.     0.     0.     1.   ]]
(x=1.414 y=-1.000 z=0.000)
(x=0.000 y=-0.414 z=0.000)
(x=2.000 y=0.414 z=0.000)
(x=0.586 y=1.000 z=0.000)


In [16]:
print(Point(0,0,0)@t1)

(x=0.000 y=0.000 z=0.000)


In [18]:
x1=l1.p
print(x1@t1.m)
t1.m[3][0]=100
print(t1)
print(l1@t1)
t2=Transform().xlate(Point(0,100,0))
print(t2)
print(Point(0,0,0)@t2)
                     

[101.15845593   0.81115958   0.           1.        ]
[[  0.985  -0.174   0.      0.   ]
 [  0.174   0.985   0.      0.   ]
 [  0.      0.      1.      0.   ]
 [100.      0.      0.      1.   ]]
(x=101.158 y=0.811 z=0.000)
[[  1.   0.   0.   0.]
 [  0.   1.   0.   0.]
 [  0.   0.   1.   0.]
 [  0. 100.   0.   1.]]
(x=0.000 y=100.000 z=0.000)


In [9]:
from leg import *
from params import *
from robot import init
init()
leg1 = QuadLeg(1, 'fr', Point(), 2, 2, ServoIds(1,2,3))
from itertools import product
x = [-1, -0.8, -0.6, -0.4, -0.2, 0, 0.2, 0.4, 0.6, 0.8, 1]
y = x
z = [-1, -1.2, -1.4, -1.6, -1.8, -2, -2.2, -2.4, -2.6, -2.8]
for p in product(x,y,z):
    pp = Point(*p)
    a = leg1.get_angles(pp)
    ppp = leg1.get_toe_pos(a)
    if ppp!= pp:
        print(pp, ppp, a)
print("Done!")

Done!
